WPF permanent delete confirmation
Ruben2776/PicView pull request #175
Opened 2024-11-15 20:28 UTC by phamduylong

## Description
Display a message box for WPF version of the app when user attempted to delete a file permanently.

## Motivation and Context
Partly solves #171

## Screenshots (if appropriate):
![image](https://github.com/user-attachments/assets/ccebf54d-d0ca-4b18-85cc-81bbacf00c4d)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-11-16 07:40 UTC, Ruben2776 requested changes

2024-11-16 07:40 UTC, Ruben2776 commented on src/PicView.WPF/FileHandling/DeleteFiles.cs
> +using System.Windows.Forms;
`MessageBox` should use `System.Windows` and not `System.Windows.Forms`.

2024-11-16 09:07 UTC, phamduylong commented on src/PicView.WPF/FileHandling/DeleteFiles.cs
> +using System.Windows.Forms;
You're right. Thanks.

2024-11-18 17:41 UTC, Ruben2776 commented
Thank you very much!

2024-11-18 17:41 UTC, merged